---
# tasks file for tomcat
  - name: download tomcat 
    get_url: url=https://www-eu.apache.org/dist/tomcat/tomcat-7/v7.0.92/bin/apache-tomcat-7.0.92.tar.gz dest=/opt
  - name: shell
    shell: "tar -xf /opt/apache-tomcat-7.0.92.tar.gz -C  /opt"
  - name: tmelate
    template: src=files/tomcat-users.xml dest=/root/apache-tomcat-7.0.92/conf
  - name: copy template for tomcat service
    template: src=tomcat.service  dest=/etc/systemd/system/tomcat.service
  - name: start service 
    service: name=tomcat state=started


